queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=2"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label=automerge
      - base=main
      - "#approved-reviews-by>=2"
      - check-success=lint
      - check-success=build
      - check-success=code_cov
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
           {{ title }} (#{{ number }})
           {{ body }}
  - name: delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch:
