apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.labels" . | indent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: api-server
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
{{- include "ports.pod" . | indent 8 }}
          env:
            - name: DEMERIS-API_LISTENADDR
              value: 0.0.0.0:{{ .Values.ports.http }}
            - name: DEMERIS-API_DATABASECONNECTIONURL
              value: "{{ .Values.databaseConnectionURL }}"
            - name: DEMERIS-API_REDISADDR
              value: "{{ .Values.redisUrl }}"
            - name: DEMERIS-API_DEBUG
              value: "{{ .Values.debug }}"
            - name: DEMERIS-API_SENTRYDSN
              value: "{{ .Values.apiServer.sentryDSN }}"
            - name: DEMERIS-API_SENTRYENVIRONMENT
              value: "{{ .Values.apiServer.sentryEnvironment }}"
            - name: DEMERIS-API_SENTRYSAMPLERATE
              value: "{{ .Values.apiServer.sentrySampleRate }}"
            - name: DEMERIS-API_SENTRYTRACESSAMPLERATE
              value: "{{ .Values.apiServer.sentryTracesSampleRate }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 10
