// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	cache "k8s.io/client-go/tools/cache"

	mock "github.com/stretchr/testify/mock"
)

// GenericInformer is an autogenerated mock type for the GenericInformer type
type GenericInformer struct {
	mock.Mock
}

// Informer provides a mock function with given fields:
func (_m *GenericInformer) Informer() cache.SharedIndexInformer {
	ret := _m.Called()

	var r0 cache.SharedIndexInformer
	if rf, ok := ret.Get(0).(func() cache.SharedIndexInformer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.SharedIndexInformer)
		}
	}

	return r0
}

// Lister provides a mock function with given fields:
func (_m *GenericInformer) Lister() cache.GenericLister {
	ret := _m.Called()

	var r0 cache.GenericLister
	if rf, ok := ret.Get(0).(func() cache.GenericLister); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.GenericLister)
		}
	}

	return r0
}
