image: emeris/api-server:latest
imagePullPolicy: Always

replicas: 3

nodeSelector: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

ports:
  http: 8000

databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

redisUrl: redis-master:6379

debug: true

serviceMonitorEnabled: true
serviceMonitorLabels:
  release: monitoring-stack

hpaMinReplicas: 3
hpaMaxReplicas: 5
hpaAverageMemoryUtilization: 90

apiServer:
  # no value means sentry is disabled
  sentryDSN:
  sentryEnvironment: local
  sentrySampleRate: 1.0
  sentryTracesSampleRate: 0.3
