name: Generate Swagger

on:
  workflow_dispatch:
  push:
    paths:
      - cmd/**
      - cns/**
      - utils/**
      - go.mod
      - go.sum

jobs:
  generate-swagger:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup token for pulling from private repos
        run: |
          go env -w GOPRIVATE=github.com/emerishq,github.com/allinbits
          git config --global url."https://git:${{ secrets.TENDERBOT_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Generate swagger
        run: make generate-swagger

      - name: Upload Swagger
        if: contains(github.ref, "/main")
        uses: actions/upload-artifact@v3
        with:
          name: swagger.yaml
          path: docs/swagger.yaml