name: Generate Swagger

on: [push]
permissions:
  contents: read
env:
  GOPRIVATE: "github.com/allinbits/*"
  GIT_TOKEN: ${{ secrets.TENDERBOT_GIT_TOKEN }}

jobs:
  swagger:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Generate swagger
        run: |
          git config --global url."https://git:${GIT_TOKEN}@github.com".insteadOf "https://github.com" &&
          make generate-swagger

      - name: Upload Swagger
        uses: actions/upload-artifact@v2
        with:
          name: swagger.yaml
          path: docs/swagger.yaml